In [1]:
import numpy as np
from hftbacktest.data.utils import databento

In [14]:
import os 
base_path = os.getcwd()
path = os.path.join(base_path, 'data/mbp.parquet')
data = databento.convert(path)[100:]

Correcting the latency
Correcting the event order


In [13]:
np.set_printoptions(formatter={'all':lambda x: str(x)})
data = data - data[0]
print(data[35:55])

[[0.0 456000.0 456000.0 0.0 39400000000.0 0.0]
 [0.0 467000.0 467000.0 2.0 40400000000.0 0.0]
 [0.0 467000.0 467000.0 2.0 40600000000.0 0.0]
 [0.0 467000.0 467000.0 0.0 39600000000.0 0.0]
 [0.0 467000.0 467000.0 0.0 39400000000.0 0.0]
 [0.0 467000.0 467000.0 0.0 39200000000.0 0.0]
 [0.0 467000.0 467000.0 2.0 40400000000.0 0.0]
 [0.0 467000.0 467000.0 2.0 40600000000.0 0.0]
 [0.0 467000.0 467000.0 2.0 40800000000.0 0.0]
 [0.0 467000.0 467000.0 0.0 39600000000.0 0.0]
 [0.0 467000.0 467000.0 0.0 39400000000.0 0.0]
 [0.0 467000.0 467000.0 0.0 39200000000.0 0.0]
 [1.0 5494000.0 5495000.0 0.0 164190000000.0 -3991.0]
 [1.0 6730000.0 6730000.0 0.0 164190000000.0 -3950.0]
 [1.0 6731000.0 6731000.0 0.0 164010000000.0 -3900.0]
 [0.0 9027000.0 9027000.0 2.0 -260000000000.0 -2000.0]
 [0.0 9027000.0 9027000.0 2.0 -259800000000.0 -2000.0]
 [0.0 9027000.0 9027000.0 0.0 -262800000000.0 -2000.0]
 [0.0 9027000.0 9027000.0 0.0 -263000000000.0 -2000.0]
 [0.0 9027000.0 9027000.0 0.0 -263200000000.0 -2000.0]

In [ ]:
from hftbacktest.data.utils import create_last_snapshot


data = create_last_snapshot("/Users/danny/projects/hftbacktest/test_dbn.npz", tick_size=0.01, lot_size=0.001)
np.savez(path + 'bn_eod.npz', data=data)

# create_last_snapshot(
#     '/Users/coopergamble/Desktop/usc/clubs/quant/hftbacktest/test_dbn.npz',
#     tick_size=0.01,
#     lot_size=0.001,
#     initial_snapshot='btcusdt_20230404_eod.npz',
#     output_snapshot_filename='btcusdt_20230405_eod'
# )